### ISSUE TITLE
report and presentation

### ISSUE THREAD

**Issue by wendtke** [nmonhait/westnile_epi#7]
write report in rmd and create presentation in R pres

**Comment by jjstudy6** [comment]
@wendtke @nmonhait @randyxun 
hi team, I had most of the report done, but needs to add a couple more small sections (from today's project update) and extend the troubleshooting part. I will post what i have so far, feel free to take a look at it and leave comments. but no rush on it, since i am still working on it 
I just got my computer back, so trying to see if i can push them, if not, Nicole, if you don't mind I will send you what i have so far and if you could help upload them.
I am sorry that i couldn't be here at the beginning of the project and having so much trouble with my computer. But i truly appreciate all your patients with me and would love to help out as much as i can.

thanks and nice evening :)

**Comment by jessyjj** [comment]
hi team, I had most of the report done, but needs to add a couple more small sections (from today's project update) and extend the troubleshooting part. I will post what i have so far, feel free to take a look at it and leave comments. but no rush on it, since i am still working on it
I just got my computer back, so trying to see if i can push them, if not, Nicole, if you don't mind I will send you what i have so far and if you could help upload them.
I am sorry that i couldn't be here at the beginning of the project and having so much trouble with my computer. But i truly appreciate all your patients with me and would love to help out as much as i can.

thanks and nice evening :)

**Comment by wendtke** [comment]
@jessyjj 
where are you pushing the report? I don't see it yet

**Comment by jessyjj** [comment]
@wendtke 
i just installed rstudio, everything was deleted, i haven't got to that step yet.

**Comment by jessyjj** [comment]
@nmonhait 
Nichole, I sent you an email last night with the drafts, wonder if you got them? thanks

**Comment by nmonhait** [comment]
@jessyjj can you please resend to nichole.monhait@colostate.edu

i will be back at my computer ~7pm tonight, will upload report

**Comment by jessyjj** [comment]
@nmonhait 
just did, thanks a lot. :)

**Comment by nmonhait** [comment]
docs are up

**Comment by jessyjj** [comment]
thanks for all the feedback, i will clean up one more time tonight and send to everyone, once everyone agrees i will turn it in

**Comment by wendtke** [comment]
I am not done with the app, if that has any bearing on when we submit a draft.

**Comment by wendtke** [comment]
@jessyjj 

Can we embed the Shiny app within the R Presentation like this? 

** example code ** 

```{r, echo = FALSE}
shinyAppDir(
  system.file("examples/06_tabsets", package="shiny"),
  options = list(width = "100%", height = 700)
)
```

For the R Markdown, we might be able to do inline code to source from the app subdirectory. Not sure.

**Comment by jessyjj** [comment]
@wendtke  these are the images of maps 2005 to 2012
<img width="615" alt="2012" src="https://user-images.githubusercontent.com/44443619/49701696-b5551980-fbac-11e8-9c0a-1ec40e861346.png">
<img width="615" alt="2011" src="https://user-images.githubusercontent.com/44443619/49701697-b5551980-fbac-11e8-9dc0-213474c0bc2b.png">
<img width="615" alt="2010" src="https://user-images.githubusercontent.com/44443619/49701698-b5551980-fbac-11e8-8bcb-78c5ede32d6f.png">
<img width="616" alt="2009" src="https://user-images.githubusercontent.com/44443619/49701699-b5551980-fbac-11e8-9af3-4bd88e12fe3b.png">
<img width="615" alt="2008" src="https://user-images.githubusercontent.com/44443619/49701700-b5551980-fbac-11e8-9279-68a059b67482.png">
<img width="615" alt="2007" src="https://user-images.githubusercontent.com/44443619/49701702-b5551980-fbac-11e8-9dc8-d1f2a3948a5b.png">
<img width="615" alt="2006" src="https://user-images.githubusercontent.com/44443619/49701703-b5551980-fbac-11e8-8f06-d1ccfc4f40ec.png">
<img width="615" alt="2005" src="https://user-images.githubusercontent.com/44443619/49701704-b5edb000-fbac-11e8-9f02-04578fa7afc7.png">

**Comment by wendtke** [comment]
I can't push them like this. If you can't, email them to me and I will upload them to the subdirectory.
